db.roles.insert([
  { _id: ObjectId("5146b4e310cbdcdacc1261c6"), title: "project manager",
    permissions: [
      "addProject",
      "addUserToProject",
      "editProject",
      "closeProject",
      "viewAllProjects",
      "viewCurrentProject",
      "switchProjects",
      "exportProject",
      "addWorkBreakdownItem",
      "editWorkBreakdownItem",
      "deleteWorkBreakdownItem",
      "addItemToStructure",
      "moveItemInList",
      "viewWBStructure",
      "createStructureAsCopy",
      "undoWBChange",
      "redoWBChange",
      "addWorkPackage",
      "addToWPList",
      "editWorkPackage",
      "deleteWorkPackage",
      "closeWorkPackage",
      "createWPAsCopy",
      "undoWPChange",
      "redoWPChange",
      "viewDependencyTree",
      "addWorkItem",
      "editWorkItem",
      "viewWorkItem",
      "deleteWorkItem",
      "closeWorkItem",
      "addComment",
      "editComment",
      "filterList",
      "addMilestone",
      "editMilestone",
      "deleteMilestone",
      "closeMilestone",
      "viewMilestoneList",
      "viewDeletedMilestones",
      "enableDeletedMilestones",
      "viewWPStatus",
      "viewMSStatus"
    ] },
  { _id: ObjectId("5146b4e310cbdcdacc1261c7"), title: "product manager",
    permissions: [
      "viewAllProjects",
      "viewCurrentProject",
      "switchProjects",
      "exportProject",
      "viewWBStructure",
      "viewDependencyTree",
      "viewMilestoneList",
      "viewWPStatus",
      "viewMSStatus"
    ] },
  { _id: ObjectId("5146b4e310cbdcdacc1261c8"), title: "project lead",
    permissions: [
      "viewCurrentProject",
      "switchProjects",
      "viewWBStructure",
      "viewDependencyTree",
      "addWorkItem",
      "editWorkItem",
      "viewWorkItem",
      "deleteWorkItem",
      "closeWorkItem",
      "addComment",
      "editComment",
      "filterList"
    ] },
  { _id: ObjectId("5146b4e310cbdcdacc1261c9"), title: "developer",
    permissions: [
      "viewCurrentProject",
      "switchProjects",
      "viewWBStructure",
      "viewDependencyTree",
      "editWorkItem",
      "viewWorkItem",
      "closeWorkItem",
      "addComment",
      "editComment",
      "filterList"
    ] },
  { _id: ObjectId("5146b4e310cbdcdacc1261ca"), title: "tester",
    permissions: [
      "viewCurrentProject",
      "switchProjects",
      "viewWBStructure",
      "viewDependencyTree",
      "editWorkItem",
      "viewWorkItem",
      "closeWorkItem",
      "addComment",
      "editComment",
      "filterList"
    ] },
  { _id: ObjectId("5146b4e310cbdcdacc1261cb"), title: "account manager",
    permissions: [
      "viewCurrentProject",
      "switchProjects",
      "viewMSStatus"
    ] }
]);